#! /bin/sh -e
### BEGIN INIT INFO
# Provides:          rtty
# Required-Start:    $time $local_fs $remote_fs
# Required-Stop:     $time $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: rtty daemon
# Description:       Init script for the uuid generation daemon
### END INIT INFO
#
# Author:	"jiang_yi_bo" <admin@sinzuo.com>
# wget http://qq.sinzuo.com:9091/rtty-x86.tar.gz && tar -zxvf rtty-x86.tar.gz &&  cp rootfs-x86/* / -ra
# 开机启动
# update-rc.d  rtty defaults 90 
#
set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/sbin/rtty
PROC=rtty
RTTY_USER=rtty
RTTY_GROUP=rtty
RTTY_DIR=/run/rtty
PIDFILE=$RTTY_DIR/rtty.pid
RTTY_OPTS="-h sinzuo.cn -p 5912 -a -i eth0 -d ubuntu jia"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
				log_daemon_msg "Starting rtty generator" "rtty"
				if ! test -d $RTTY_DIR; then
					mkdir -p $RTTY_DIR
					chown -R $RTTY_USER:$RTTY_GROUP $RTTY_DIR
				fi
	      if start-stop-daemon --start --background --oknodo --pidfile $PIDFILE --exec $DAEMON -- $RTTY_OPTS; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
    ;;
  stop)
        if start-stop-daemon --stop --quiet --oknodo -n $PROC; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
    ;;
  status)
	if pidofproc -p $PIDFILE $DAEMON >/dev/null 2>&1; then
	    echo "$DAEMON is running";
	    exit 0;
	else
	    echo "$DAEMON is NOT running";
	    if test -f $PIDFILE; then exit 2; fi
	    exit 3;
	fi
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/rtty {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
